### PR TITLE
feat(community-features): community 2.0 + forums update + classes

### PR DESCRIPTION
**Pull request by FedeIlLeone**
> ~**:warning: Keeping this PR in draft until these new features seem stable enough**~

This PR themes new server features such as Channel Browser and Customization Questions.

**Notes:**
Unfortunately, I didn't use the modal-background variable on the onboarding modal, as amoled-cord v3 doesn't change it. So it will be fixed right with v4.

**Screenshots:**
before-customize
after-customize
before-browser
after-browser
before-onboarding-modal
after-onboarding-modal

### CODE REVIEW

**Comment by FedeIlLeone** [comment]
lgtm

**Comment by FedeIlLeone** [comment]
F* I didn't want to delete 😢

**Comment by LuckFire** [comment]
I knew I was forgetting to do something.

**Comment by FedeIlLeone** [comment]
oops, I'll take a look in a few mins. Some things may have changed.

**Comment by FedeIlLeone** [comment]
👍🏻 LGTM.

Fixed modals and some classes that were changed.

**Pull request merged**
