### PR TITLE
Changed some things and new stuff themed

### PR DESCRIPTION
**Pull request by FedeIlLeone**
I've been working on this for about a week, but then the owner published #36 , so I create a new one 😉.
This pull request has some changes on most parts of the app, and also themed some areas that were not.
I'm keeping this a draft PR for a while.

~*I'm posting screenshots tomorrow*~

**Changes made:**
- Global variables:
  - Applied them to light theme for server create modal (why Discord hasn't done a dark themed modal of that yet??)
  - Changed background modifiers to make them updated with Discord's accessibility change made a week ago.
  - Discord added a new variable to make all inputs the same, so it's now used in the theme as well.
- Experiments:
  - Forums themed; these new types of channels are publicly available on some servers, so why not theme them already.
  - Home tab; this is not available to everyone yet, but I themed it.
- Most of the pages have been updated to make them as similar to how Discord would like them (e.g. the colors between them); still respecting the colors of this theme.
  - Boost page, guild audit log, some sections in settings, search in guild, pinned messages, inbox, slash commands.
- Server create modal redraw.
- Other changes:
  - People in voice indicator themed.
  - Bar sliders themed (e.g. the slider found in slowmode settings).
  - Keybind set input fixed.
  - Invite friends tile themed (found in voice call when alone).
  - Changed a few modals: student hub, server join from link, server leave feedback, membership screening, event info (suggestion from #33), screenshare.

Regarding the forums and the home tab, maybe I should remove them from this PR and move it to a dedicated one for the future when they are actually released to the public (?)

**Forums:**
forums
**Home Tab (full):**
home-tab-full
**Home Tab (when width <1300):**
home-tab-mini
**Server create modal:**
server-create
**Modals 1**:
modals
**Modals 2:**
modals-2

### CODE REVIEW

**Comment by FedeIlLeone** [comment]
**Changes made between commit 568731013adfd5d84ca82ad6d50e74efbf876bba and 13de4609ad8b1b524bb660550b080a35093b41de:**
changes-1

*I messed up with commits, that's why there are some reverts*

**Comment by FedeIlLeone** [comment]
**Changes made on commit 32e1c28e0eb92952168efc0cbc9875bff891de7e:**
- Account switcher themed; it seems they are releasing it to the public or a small group of people.

account-switcher

**Comment by FedeIlLeone** [comment]
**Changes made on commit 3cc4eb2e7107db122a1487de01dcde3c172af8d8:**
- Classes fix.
- Add servers to student hub fixed.
- Invite banner upsell themed.
- Server discovery settings themed.

changes-2

**Comment by FedeIlLeone** [comment]
**Changes made on commit ff53e49fe22539e79b612367f5f0fa3a7fe4908f:**
- Color picker themed.
- Server template preview themed.

changes-3

**Comment by FedeIlLeone** [comment]
**Changes made between commit d42945293ddb47aebf562d8d8c1e7e469522e934 and f9edd2abbac19765c9fc48e2720613e404ecca22:**
- Fixed file upload input; hover prop. was shared with the keybind set input.
- Home feed events card themed.
- Fixed bar sliders; microphone sensitivity.
- Fixed attachments on the post create text box in forums channels.
- Add bot to server modal themed.
- Tooltips themed.

**Comment by FedeIlLeone** [comment]
LGTM.

I don't know if it is needed to bump the theme version. I think it already had to be done with #36 as it had many fixes.
Regarding the forums and the home feed, at the time of writing this comment, everything is correctly themed, I don't know if anything could change later. Both are currently usable and are found on some specific servers.

**Comment by LuckFire** [comment]
Sick👍 

Appreciate your help and effort btw

**Pull request merged**
